### ISSUE TITLE
Add Debugging support

### ISSUE THREAD

**Issue by obiwan87** [obiwan87/odin-intellij#68]
## Tasks

- [x] Separate projects such that community edition can still run without debugging (see ZigBrains, IntelliJ-Rust)
- [x] Provide settings for debugger
- [x] Provide debug toolchain downloader and debug toolchain settings
   - [x] MS debugger
   - [ ] LLDB-DAP debugger
- [x] Test native LLDB driver on 
    - [x] MacOs
    - [x] Linux
- [x] Test LLDB-DAP driver on Linux/MacOs
    - [x] MacOs
    - [x] Linux
## Fixes/Issues
- [ ] #70
- [ ] #71
- [x] Investigate why LLDB driver does not work out-of-the-box

**Comment by obiwan87** [comment]
@timlueg Binary needs to be build first and then attached when starting the debug session.

**Comment by obiwan87** [comment]
Here are my latest findings: 

- I could not get the lldb driver to work with Odin on windows
- however, I could get lldb to work within the visual studio dev prompt
- Odin does not support Gen
- I was able to debug Odin with MSVC
- the zig plugin uses MSVC + DAPDriver to integrate debugging within IntelliJ
- the DAPDriver is part of the Zig plugin code base. I have already asked for permission to re-use it 

@timlueg do you have a Linux machine? It would be nice to test if the lldb driver works there.

**Comment by timlueg** [comment]
>  it incomptabile with community edition.  

Yes I defined the plugin as optional in the .xml but have not evaluated it yet. Will probably also require some changes to the build.gradle.kts. Maybe something similar whats done here https://github.com/vlang/intellij-v/blob/main/build.gradle.kts

> Binary needs to be build first

Yes, I wasn't sure how you want to structure this yet. I saw you already implemented it now. I just quickly tested your changes and noticed that now it does not correctly start the debugger or at least it does not stop at the breakpoint anymore. I can get it to work again by setting: `commandLine.setExePath(pathToExecutable)`. You also want to use `addCommandPart(command, "build");` instead of `addCommandPart(command, "run");` in this case.

(I can create a merge request if you haven't already done so before I find the time.)

**Comment by obiwan87** [comment]
> Yes I defined the plugin as optional in the .xml but have not evaluated it yet. Will probably also require some changes to the build.gradle.kts. Maybe something similar whats done here https://github.com/vlang/intellij-v/blob/main/build.gradle.kts

yes, absolutely right.

> You also want to use addCommandPart(command, "build"); instead of addCommandPart(command, "run"); in this case.
You can disregard my commit, as in that scenario the output of the build process is not shown on the console. I'm trying to find a possibility to do so.

**Comment by obiwan87** [comment]
Anyway: these are my findings re debugging:

- gdb is not supported by ODin
- lldb is supported, but the IntelliJ implementation doesn't seem to work
- The developer of the zig plugin has allowed us to use his [DAPDriver](https://github.com/FalsePattern/ZigBrains/blob/master/modules/debugger/src/main/java/com/falsepattern/zigbrains/debugger/dap/DAPDriver.java), which would allow to use the lldb-dap tool by LLVM and other DAP-compatible debuggers

**Comment by obiwan87** [comment]
LLDB-DAP works. Need a place to host it and also figure out what dependencies it has.

**Comment by obiwan87** [comment]
> Looks like here they got LLDB to work using the native debug plugin: https://github.com/vlang/intellij-v

Would be ideal to get the native driver working. however, for me it doesn't. Maybe it's an OS thing? Do you have a Linux system?

**Comment by obiwan87** [comment]
Debuggers work on every major OS. Bundled LLDB on Linux doesn't work on GoLand apparently but LLDB-DAP does

**Comment by timlueg** [comment]
> Maybe it's an OS thing? Do you have a Linux system?

Yes I'm on Linux using Clion. I can now also confirm that LLDB works under CIDR using `LLDBDriverConfiguration`. With LLDB instead of GDB it now automatically loads variables in the Threads&Variables watch window.

(For this test I manually build the executable with -debug, as we know that OdinRunCommandLineState wasn't working yet. I have not looked at your recent changes but happy you got debugging working.


![image](https://github.com/user-attachments/assets/48a861af-7700-40c1-b7b4-90a3112fd110)

**Comment by obiwan87** [comment]
As of the newest version, that you can get from the marketplace, debugging is now fully integrated, including the debug build prior to starting the the debug process. I had LLDB and LLDB DAP tested on macOS, too. They also work there.
